### ISSUE TITLE
get_device_config fails if uniq is NULL

### ISSUE THREAD

**Issue by KWottrich** [v1993/evdevhook2#13]
I'm working on getting Gyro support added for the ASUS ROG Ally.  We have a working kernel driver that outputs to iio, and I've created a program that translates the raw iio output into an evdev device using uinput (https://github.com/KWottrich/ally-motion-evdev).  When trying to use my uinput device with evdevhook2, I'm getting an assertion failure because uinput doesn't support setting the uniq attribute of your device:

`** (evdevhook2:16302): CRITICAL **: 11:36:45.907: evdevhook_config_get_device_config: assertion 'uniq != NULL' failed`

I have verified that I can work around this by manually assigning a mac address (which doesn't seem to ever get used...?) and changing get_device_config to skip the lookup by uniq and always `return allowlist_mode ? null : new DeviceConfig();`

**Comment by v1993** [comment]
Interesting... is it actually impossible to set a proper uniq? It's used both for persistent controller identification across sessions by clients as mac (see [gcemuhook](https://github.com/v1993/gcemuhook) library for code that handles that) and config lookup.

It's definitely possible to handle this case and I'll look into it - I did not solely because every other motion driver I know sets this field, but it would be preferable to supply a proper uniq on your end.

**Comment by v1993** [comment]
Should be fixed now. Please report if you'll encounter any further issues.

**Comment by v1993** [comment]
Oh, and FYI - https://github.com/v1993/evdevhook2/commit/0574c0fd354e2f3501eb80f833b7355619d1165b is very wrong for a variety of reasons. On top of breaking per-device configuration it also potentially exposes multiple devices with the same MAC, which is forbidden by cemuhook protocol (unless MAC is zero, which corresponds to it not being available, which is what my fix reports for null uniq case).

**Comment by KWottrich** [comment]
Thanks for addressing this so quickly! I appreciate the explanation about the Cemuhook protocol as well. My fork was meant to be a quick hack for a proof of concept, and I'm grateful to have the proper fix in your project!
